version: '3'

services:
  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./docker/nextcloud/nc-data:/var/www/data
      - ./docker/nextcloud/html:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - PHP_MEMORY_LIMIT=5G
      - PHP_UPLOAD_LIMIT=5G
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
      - s3.env    # デフォルトでS3を使う時の。使わない場合はコメントアウト
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    restart: always

  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Pa55W0rd
    env_file:
      - db.env
  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./docker/nextcloud/data:/var/www/data
      - ./docker/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
